version = "3.7.14"
runner.dialect = scala3
maxColumn = 100
align.preset = more
align.multiline = true
continuationIndent.defnSite = 2
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
lineEndings = preserve
includeCurlyBraceInSelectChains = false
danglingParentheses.preset = true
spaces {
  inImportCurlyBraces = true
}
optIn.annotationNewlines = true
rewrite.rules = [Imports, SortModifiers, PreferCurlyFors]
rewrite.imports.sort = scalastyle